### PR TITLE
Add "Quick Ship Entire Order" button on OrderDetails screen

### PR DESCRIPTION
**Pull request by zhangwei1979**

### CODE REVIEW

**Comment by jonesde** [comment]
This was on the OrderDetail screen a long time ago and was removed because for most business scenarios this is a very bad idea and causes operational issues.

What is the business scenario you have in mind for this?

**Comment by zhangwei1979** [comment]
As you mentioned in google group for phisical POS, I think there should be a way let user know how to fulfill order created by POS

**Comment by jonesde** [comment]
Yes, in a POS application that service would be one way to handle the inventory side of the in-person 'fulfillment'. The OrderDetail screen is not part of a POS app, it's part of a set of screens (in SimpleScreens) for use in an ERP app and really isn't designed for use on a point of sale system. This would be one of many things that would be different for point of sale. In other words, I don't think that's an adequate reason to include this on the OrderDetail screen.

**Comment by zhangwei1979** [comment]
Understood. I close this pr then

**Pull request closed without merging**
