### PR TITLE
Add first version of lead screens and also sales-funnel.

### PR DESCRIPTION
**Pull request by tukaws**
These changed is a change from @hansbak for lead screens and functionality moving block on sales-funnel. I'm Tuk who work for AntWebsystems Co.,Ltd and I take care of this implementation.

Please feel free to add your comments.

### CODE REVIEW

**Comment by jonesde** [comment]
There is a lot to review here, looks like great progress!

My notes on the mantle-udm pull request related to this all apply to this pull request and were never addressed there:

https://github.com/moqui/mantle-udm/pull/71

Along with that the SimpleScreensDemoData.xml file should not exist, demo data related to Mantle data model or services should go in mantle-usl along with other demo data files. The general idea is that SimpleScreens is built on mantle-udm and mantle-usl but those two components can be used independently. Think of it in terms of the REST API only use case if that helps.

The drag and drop stuff adds a lot of overhead. The better way to use external JS is not to commit the full source but rather (as is done for all JS libraries not used in the XML Screen FTL macros) is to use a cdnjs URL in a script element in the inline source. With this approach the SimpleScreens source isn't cluttered by dozens of infrequently used JS and CSS files, and we know they are used stock as opposed to possibly having some undocumented changes that are likely to get lost over time (best avoided unless necessary, and then like in moqui-runtime there are README and patch files to document the differences).

Another thing I don't like having in there so much is the letter images... an extra 26 images. Is there a reason these can't be done with plain text and some simple CSS styling?

**Comment by jonesde** [comment]
How does this relate to pull request #88 ? Does this pull request replace that one (ie PR #88 can be closed)?

**Comment by zhangwei1979** [comment]
I don't think LeadServices.xml should be put in SimpleScreens component

**Comment by jonesde** [comment]
Good point, and I don't see much value add in that service vs a direct call of mantle.party.PartyServices.update#PartyDetail. Services in general should go in mantle-usl, if needed. This service (update#UpdatePartyStatus) also has an redundant name and the 'newStatus' parameter is non-standard, almost have to look at the code of the service to see what it does (no hints in the service name or the parameter name), a better parameter name would be the field it is meant for: customerStatusId.

**Comment by hansbak** [comment]
con cancel this one, person is not working in our company anymore

**Comment by danieltaylor-nz** [comment]
Shame to lose so much work, but maybe this can be re-done by someone in the future.

**Pull request closed without merging**
