### PR TITLE
Added Survey screens to create survey form, form field and form preview.

### PR DESCRIPTION
**Pull request by nirendra10695**
Added Survey screens to create survey form, form field and form preview.

### CODE REVIEW

**Comment by zhangwei1979** [comment]
May I know where is the entrance of this function?

**Comment by nirendra10695** [comment]
For the entrance of this functionality I submitted pull request [#35](https://github.com/moqui/PopCommerce/pull/35/files) in PopCommerce repository and one more pull request [#325](https://github.com/moqui/moqui-framework/pull/325) in moqui-framework which is related to this functionality..

**Comment by zhangwei1979** [comment]
The entity view DbFormAndUserGroup and service org.moqui.impl.ScreenServices.get#FormResponseStats are lost

**Comment by nirendra10695** [comment]
Check Pull request [#325](https://github.com/moqui/moqui-framework/pull/325) in moqui-framework Github repository.

**Comment by zhangwei1979** [comment]
Why not we have this feature applying to all type DbForm?

**Comment by nirendra10695** [comment]
Currently we have valid and real world requirement([check here](https://www.moqui.org/vapps/hm/wiki/apps/Planning+and+Designs/Survey+Screens)) only for Survey Screens in PopCommerce application. So thats why I added this feature only for Survey screens. If you have any implementation plan for different types of DbForm then you can suggest on community forums(moqui-application google group or [moqui.org](https://www.moqui.org)).

**Comment by zhangwei1979** [comment]
I think it is easy we add purpose type dropdown in Create/Edit Survey(DbForm) screen and have it applying to all type DbForm.

<field name="purposeEnumId"><default-field title="Purpose">
                            <widget-template-include location="component://webroot/template/screen/BasicWidgetTemplates.xml#enumDropDown">
                                <set field="enumTypeId" value="DbFormPurpose"/>
                            </widget-template-include></default-field></field>

**Comment by zhangwei1979** [comment]
One more thing, Find button is missed in Find Options popup

**Comment by nirendra10695** [comment]
This functionality is only for Survey(enumTypeId = DbfpSurvey) which is one of DBFormPurpose. So, How we can add purpose type dropdown in Create/Edit Survey(DbForm) screen.

 I am agree with @zhangwei1979  requirements but for your requirements we need to generalise the screen name(like FindDbForm, EditDbForm etc) and also entry point of the DbForm functionality we need to decide. 

@jonesde what is your views on @zhangwei1979 requirements?

**Comment by jonesde** [comment]
Thank you Nirendra for working on this, and thank you Zhang for reviewing and offering feedback. 

On the topic of generic DbForm screens vs these Survey screens my thought is that it does make sense to have more general screens in the System app and while they could be similar they would have differences and more likely diverge over time for different use cases and target audiences. For example there are lots of fields on the DbFormField entity for layout and such and those make no sense on these screens, but should be on the screens in the System app.

BTW, one thing I'm considering is a new Admin app or possibly an Admin/Setup section of the POPC ERP app that would have some things in the System app and some things removed from POPC ERP, mostly configuration sorts of things.

Anyway, from a brief review I think this is fine for an initial implementation of these screens.

**Pull request merged**
